# Generated by Django 5.1.5 on 2025-02-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
