# Generated by Django 5.1.5 on 2025-02-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bookings_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='event_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
