# Generated by Django 5.1.5 on 2025-04-07 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bookings_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='decoration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.decoration'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.food'),
        ),
    ]
